version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: crypto-up
    restart: always
    ports:
      - $APP_PORT:$APP_PORT
    environment:
      - DB_HOST=$DB_HOST
      - DB_PORT=$DB_PORT
      - DB_NAME=$DB_NAME
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    ports:
      - $DB_PORT:$DB_PORT
    environment:
      - POSTGRES_DB=$DB_NAME
      - POSTGRES_USER=$DB_USER
      - POSTGRES_PASSWORD=$DB_PASSWORD
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

# docker-compose build --no-cache && docker-compose up -d
